[package]
name = "dosensuppe/eventbroker"
version = "2.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["examples", "examples/**"]
include = [
    "default.project.json",
    "EventBroker",
    "EventBroker/",
    "EventBroker/*",
    "EventBroker/**",
    "wally.toml",
    "wally.lock",
    "LICENSE",
    "README.md",
]
