[package]
name = "dosensuppe/eventbroker"
version = "1.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["examples", "examples/**"]
include = [
    "src",
    "src/**",
    "default.project.json",
    "wally.toml",
    "wally.lock",
    "LICENSE.md",
    "README.md",
]
