[package]
name = "dosensuppe/eventbroker"
version = "2.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["examples", "examples/**", "default.project.json",]
include = [
    "src",
    "src/**",
    "wally.toml",
    "wally.lock",
    "LICENSE",
    "README.md",
]
